name: Docker Image to GitHub Packages

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Print Working Directory
      run: pwd
      
    - name: List Files
      run: ls -al
    
    - name: Setup Go environment
      uses: actions/setup-go@v2
      with:
        go-version: 1.19
      
    - name: Build
      run: go build .
      working-directory: ./cmd/go-mathify

  docker:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Login to GitHub Docker Registry
      run: echo "${{ secrets.DOCKER_BUILD_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
    
    - name: Build and Push Docker Image
      run: |
        docker build -t ghcr.io/${{ github.repository }}/go-mathify:latest .
        docker push ghcr.io/${{ github.repository }}/go-mathify:latest

