name: Go

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  DEBUG: 'false'

jobs:
  build:
    runs-on: ubuntu-20.04  # Pinning this Ubuntu version for longer-term consistency

    strategy:
      matrix:
        go-version: ['1.19']

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Debug before cache
      if: env.DEBUG == 'true'
      run: ls -al ~/go/pkg/mod

    # Remove when found unnecessary
    - name: Cleanup old cache
      if: env.CLEAR_CACHE == 'true'
      run: rm -rf ~/go/pkg/mod/*

    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go-version }}

    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Debug after cache
      if: env.DEBUG == 'true'
      run: ls -al ~/go/pkg/mod

    - name: Download dependencies
      run: go mod download

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
